### ISSUE TITLE
Typos in Lesson 2

### ISSUE THREAD

**Issue by tacolopo** [secretuniversity/scrt.university#2]
1) "Now that you have been briefed on computational privacy, you should understand that Secret Network grants you the unique ability build decentralized applications that process data privately with controls in place for access control and transparency."

should be:

"Now that you have been briefed on computational privacy, you should understand that Secret Network grants you the unique ability to build decentralized applications that process data privately with controls in place for access control and transparency."

2) "We will also explore a few use cases that privacy-preserving smart contracts unlocks."

should be:

"We will also explore a few use cases that privacy-preserving smart contracts unlock."

3) "At the end of the day, Secret Network is committed to staying at the forefront of privacy in the blockchain space and will continuously exploring new technologies as the space develops."

should be:

"At the end of the day, Secret Network is committed to staying at the forefront of privacy in the blockchain space and will continuously explore new technologies as the space develops."

It would also be nice to link to things mentioned in the lessons. For example, actually link to ALTER or the DoD article so people can learn more.

**Comment by sinplea** [comment]
Thank you for taking the time to find these issues! Your work is greatly appreciated :pray:  

I've forwarded your fixes to the pathway writer to get these fixed asap.

**Comment by sinplea** [comment]
The introductory pathway has been updated!
